title: Zhezhen's Sciart Playground # your name (or website title) here
logo: "/images/zhezhen_web_logo2.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  art and science communication 
  <br>
  creating abstract art using coding languages
  <br><br>
  <a href="www.linkedin.com/in/zhezhen-y-73a81a159">View My LinkedIn Profile</a> 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
