title: Zhezhen's Sciart Playground # your name (or website title) here
logo: "/images/zhezhen_web_logo2.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Sciart Using Coding
  <br>
  Art and Science Communication
  <br><br>
  "[About This Website](/about.md)"   
  <a href="https://www.linkedin.com/in/zhezhen-y/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
